from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from config import LabConfig, load_config
from memory_store import estimate_tokens
from model_provider import build_chat_model


@dataclass
class SessionState:
    messages: list[dict[str, str]] = field(default_factory=list)
    token_usage: int = 0
    prompt_tokens_processed: int = 0


class BaselineAgent:
    """Agent A / Baseline Agent.

    Characteristics:
    - Within-session (in-memory) memory only.
    - No persistent User.md profile storage.
    - Loses all context across different thread IDs (zero cross-session recall).
    - Unbounded context growth in long threads (processes all prior messages every turn).
    """

    def __init__(self, config: LabConfig | None = None, force_offline: bool = True) -> None:
        self.config = config or load_config()
        self.force_offline = force_offline
        self.sessions: dict[str, SessionState] = {}
        self.langchain_agent = self._maybe_build_langchain_agent()

    def reply(self, user_id: str, thread_id: str, message: str) -> dict[str, Any]:
        """Generate response and track token usage."""
        if self.force_offline or self.langchain_agent is None:
            return self._reply_offline(thread_id, message)

        try:
            # Live path fallback to offline if not fully configured
            return self._reply_offline(thread_id, message)
        except Exception:
            return self._reply_offline(thread_id, message)

    def token_usage(self, thread_id: str) -> int:
        """Return cumulative output token count generated by the agent for a thread."""
        session = self.sessions.get(thread_id)
        return session.token_usage if session else 0

    def prompt_token_usage(self, thread_id: str) -> int:
        """Return total cumulative prompt tokens processed for a thread."""
        session = self.sessions.get(thread_id)
        return session.prompt_tokens_processed if session else 0

    def compaction_count(self, thread_id: str) -> int:
        """Baseline agent does not have compact memory."""
        return 0

    def _reply_offline(self, thread_id: str, message: str) -> dict[str, Any]:
        """Deterministic offline reply behavior with prompt-load tracking."""
        session = self.sessions.setdefault(thread_id, SessionState())

        # Baseline carries ALL previous messages in the current thread as context
        prior_context_tokens = sum(estimate_tokens(m["content"]) for m in session.messages)
        current_msg_tokens = estimate_tokens(message)
        prompt_load = prior_context_tokens + current_msg_tokens
        session.prompt_tokens_processed += prompt_load

        # Record user message
        session.messages.append({"role": "user", "content": message})

        # Generate deterministic response
        # In a new thread, baseline has NO prior knowledge
        lower = message.lower()
        is_recall_query = any(
            kw in lower
            for kw in [
                "mình tên gì",
                "tên mình là gì",
                "ở đâu",
                "làm nghề gì",
                "đồ uống",
                "món ăn",
                "nuôi con gì",
                "style trả lời",
                "bạn biết dũngct không",
                "nhắc lại giúp mình",
                "nhắc lại style",
                "tóm tắt ngắn về mình",
                "sang thread mới",
            ]
        )

        if is_recall_query:
            # Baseline only knows what's inside this current thread
            # Check if facts were mentioned in this specific thread
            thread_text = " ".join(m["content"] for m in session.messages[:-1])
            if not thread_text.strip():
                response_text = (
                    "Xin lỗi bạn, đây là một phiên làm việc mới và mình không có bất kỳ thông tin nào "
                    "về bạn từ các phiên trước đó."
                )
            else:
                response_text = f"Trong phiên này, mình chỉ ghi nhận các tin nhắn đã trao đổi gần đây: {thread_text[:100]}..."
        else:
            response_text = "Mình đã nhận được tin nhắn của bạn trong phiên làm việc hiện tại."

        resp_tokens = estimate_tokens(response_text)
        session.token_usage += resp_tokens
        session.messages.append({"role": "assistant", "content": response_text})

        return {
            "role": "assistant",
            "content": response_text,
            "tokens": resp_tokens,
            "prompt_tokens": prompt_load,
        }

    def _maybe_build_langchain_agent(self):
        """Optionally build a live LangChain chat model."""
        if self.force_offline:
            return None
        try:
            return build_chat_model(self.config.model)
        except Exception:
            return None
